version: "3.7"
services:
  memcached:
    image: memcached:latest
    container_name: ihris_memcached
    ports:
      - "11211:11211"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: host.docker.internal
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: m0h1ct11
      MYSQL_ROOT_PASSWORD: m0h1ct11

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      MYSQL_ROOT_PASSWORD: m0h1ct11

  ihris:
    image: ihris:4.3.3
    build:
      context: .
      dockerfile: .docker/iHRIS.development.dockerfile
    container_name: ihris
    restart: 'always'
    ports:
      - "8080:80"
    volumes:
      - .:/var/lib/iHRIS/lib/4.3.3
    environment:
      IHRIS_MEMCACHED_SERVER: ihris_memcached
    depends_on:
      - memcached

networks:
  default:
      name: ihris
