version: "3.7"
services:
  db:
    image: mysql:8.0.15
    container_name: ihris_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: m0h1ct11
      MYSQL_DATABASE: ihris_manage
      MYSQL_USER: ihris
      MYSQL_PASSWORD: m0h1ct11

#  memcached:
#    image: memcached:latest
#    container_name: ihris_memcached
#    ports:
#      - "11211:11211"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 8082:80
    environment:
      PMA_HOST: ihris_mysql
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: m0h1ct11
      MYSQL_ROOT_PASSWORD: m0h1ct11

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
    environment:
      MYSQL_ROOT_PASSWORD: m0h1ct11

  ihris:
    image: ihris:4.3.3
    build:
      context: .
      dockerfile: .docker/iHRIS.development.dockerfile
    container_name: ihris
    restart: 'always'
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/var/lib/iHRIS
    environment:
      IHRIS_MEMCACHED_SERVER: ihris_memcached

networks:
  default:
    name: ihris
